[[sas]]
active = true
width = 1920
height = 1080
freq = 60.0
x = 1920.0
y = 0.0
uid = "DVI-D-1"
scale = 1.0
transform = 0

[[sas]]
active = true
width = 1920
height = 1080
freq = 74.99
x = 0.0
y = 0.0
uid = "HDMI-A-1"
scale = 1.0
transform = 0
